all:
	clang -I ./include -I ../../3rd_party/json-develop/include -I ../../3rd_party/loguru -I ../items/include  -I ../include -o ./obj/audio.o -c ./src/audio.cpp
	clang -I ./include -I ../../3rd_party/json-develop/include -I ../../3rd_party/loguru -I ../items/include -I ../include -o ./obj/effect.o -c ./src/effect.cpp
	clang -I ./include -I ../../3rd_party/json-develop/include -I ../../3rd_party/loguru -I ../items/include -I ../include -o ./obj/fragment.o -c ./src/fragment.cpp
	clang -I ./include -I ../../3rd_party/json-develop/include -I ../../3rd_party/loguru -I ../items/include -I ../include -o ./obj/session.o -c ./src/session.cpp
	clang -I ./include -I ../../3rd_party/json-develop/include -I ../../3rd_party/loguru -I ../items/include -I ../include -o ./obj/track.o -c ./src/track.cpp